### ISSUE TITLE
Issues with bad tokens in authentication-optional endpoints.

### ISSUE THREAD

**Issue by scolby33** [scolby33/wheres_charlie#5]
Some endpoints (e.g. `GET /locations`) can be accessed by unauthenticated users, but have additional features when accessed by authenticated users. As it stands now, the request proceeds as if no authentication token was provided when the provided one is invalid. Should an error be issued instead?

**Comment by cthoyt** [comment]
yeah, def give an invalid authentication error

**Comment by cthoyt** [comment]
btw the reasoning behind this is that if theres a problem with the key and somebody is trying to access, they might expect things that they won't end up getting back. better let them know
